#!/bin/bash


# Check if the system is running Linux
if [[ "$(uname)" != "Linux" ]]; then
  echo -e "\033[31mYou must run this script on Linux!\033[0m"
  exit 1
fi

# Check if there's apt
if ! command -v apt >/dev/null 2>&1; then
  echo -e "\033[31mThis script only supports Apt-based distributions!\033[0m"
  exit 1
fi

# Check if sudo is available
if ! command -v sudo >/dev/null 2>&1; then
  echo -e "\033[31mThis script requires sudo. Please install sudo package and try again.\033[0m"
  exit 1
fi

# Install wget if not already installed
if ! command -v wget >/dev/null 2>&1; then
  sudo apt update
  sudo apt install -y wget
fi

# Create directories if they don't exist
clear
echo "Making changes...."
sudo mkdir -p /etc/apt/trusted.gpg.d
sudo mkdir -p /etc/apt/sources.list.d
sleep 2

# Download and move the files
echo "Downloading...."
sudo wget -qO /etc/apt/trusted.gpg.d/microsoft.gpg "https://github.com/revx0012/vscode-linux/raw/main/repos/apt/trusted.gpg.d/microsoft.gpg"
sudo wget -qO /etc/apt/sources.list.d/vscode.list "https://raw.githubusercontent.com/revx0012/vscode-linux/main/repos/apt/sources.list.d/vscode.list"
sleep 2

# Update package manager
echo "Updating..."
sudo apt update

echo "Installation is now done, Use 'sudo apt install code' if you wish to install vscode."
